export const languages = [
    { value: "english", label: "English" },
    { value: "spanish", label: "Spanish" },
    { value: "french", label: "French" },
    { value: "german", label: "German" },
    { value: "japanese", label: "Japanese" },
    { value: "chinese", label: "Chinese" },
    { value: "russian", label: "Russian" },
    { value: "portuguese", label: "Portuguese" },
    { value: "hindi", label: "Hindi" },
    { value: "arabic", label: "Arabic" },
    { value: "italian", label: "Italian" },
    { value: "korean", label: "Korean" },
    { value: "dutch", label: "Dutch" },
    { value: "turkish", label: "Turkish" },
    { value: "swedish", label: "Swedish" },
    { value: "urdu", label: "Urdu"},
];